version: '3.8'

services:
  jaeger:
    image: jaegertracing/all-in-one:1.55
    container_name: jaeger
    environment:
      - COLLECTOR_OTLP_ENABLED=true   # bật OTLP receiver (v2-style)
      - LOG_LEVEL=debug               # gỡ lỗi nếu cần
      - MEMORY_MAX_TRACES=1000000
    ports:
      - "16686:16686"  # Jaeger UI
      - "4317:4317"    # OTLP gRPC
      - "4318:4318"    # OTLP HTTP
      - "14268:14268"  # Jaeger collector HTTP (optional)
      - "14269:14269"